[book]
authors = ["JYU"]
language = "fi"
src = "src"
title = "Ohjelmointi 1"

[output.html]
additional-css = [ 
  "highlight/atelier-forest-light.css",
  "highlight/twilight.css",
  "highlight/apprentice.css",
  "theme/alerts-style.css",
]
default-theme = "jyu-light"
preferred-dark-theme = "jyu-dark"
additional-js = [
  "mermaid/mermaid.min.js", 
  "mermaid/mermaid-init.js",
] 
site-url = "/ohj1-mdbook-demo/"

[preprocessor.alerts]

[preprocessor.mermaid]
